/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    IconApp: typeof import('./src/components/icons/IconApp.vue')['default']
    IconAppFull: typeof import('./src/components/icons/IconAppFull.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCsv: typeof import('./src/components/icons/IconCsv.vue')['default']
    IconDispatch: typeof import('./src/components/icons/IconDispatch.vue')['default']
    IconDoc: typeof import('./src/components/icons/IconDoc.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEmpty: typeof import('./src/components/icons/IconEmpty.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconHomeFull: typeof import('./src/components/icons/IconHomeFull.vue')['default']
    IconHtml: typeof import('./src/components/icons/IconHtml.vue')['default']
    IconIf: typeof import('./src/components/icons/IconIf.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconMCP: typeof import('./src/components/icons/IconMCP.vue')['default']
    IconMd: typeof import('./src/components/icons/IconMd.vue')['default']
    IconMulti: typeof import('./src/components/icons/IconMulti.vue')['default']
    IconOpenApi: typeof import('./src/components/icons/IconOpenApi.vue')['default']
    IconOpenApiFull: typeof import('./src/components/icons/IconOpenApiFull.vue')['default']
    IconPdf: typeof import('./src/components/icons/IconPdf.vue')['default']
    IconPpt: typeof import('./src/components/icons/IconPpt.vue')['default']
    IconProperties: typeof import('./src/components/icons/IconProperties.vue')['default']
    IconSingle: typeof import('./src/components/icons/IconSingle.vue')['default']
    IconSpace: typeof import('./src/components/icons/IconSpace.vue')['default']
    IconSpaceFull: typeof import('./src/components/icons/IconSpaceFull.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTool: typeof import('./src/components/icons/IconTool.vue')['default']
    IconToolFull: typeof import('./src/components/icons/IconToolFull.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconTxt: typeof import('./src/components/icons/IconTxt.vue')['default']
    IconXls: typeof import('./src/components/icons/IconXls.vue')['default']
    IconXml: typeof import('./src/components/icons/IconXml.vue')['default']
    IconYaml: typeof import('./src/components/icons/IconYaml.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
